version: 0.1.0-{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: git submodule update --init --recursive
build:
  verbosity: minimal
artifacts:
- path: Lamp.Simulator\bin\Release\